// Code generated by protoc-gen-go.
// source: HseMsg/HseMsg.proto
// DO NOT EDIT!

/*
Package HseMsg is a generated protocol buffer package.

It is generated from these files:
	HseMsg/HseMsg.proto

It has these top-level messages:
	Message
	User
	Request
	Result
	Event
	ServerMessage
*/
package HseMsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Result_SignUpResult_SignUpResultStatus int32

const (
	Result_SignUpResult_SIGNED_UP         Result_SignUpResult_SignUpResultStatus = 1
	Result_SignUpResult_USERNAME_IS_TAKEN Result_SignUpResult_SignUpResultStatus = 2
	Result_SignUpResult_VALIDATION_ERROR  Result_SignUpResult_SignUpResultStatus = 3
)

var Result_SignUpResult_SignUpResultStatus_name = map[int32]string{
	1: "SIGNED_UP",
	2: "USERNAME_IS_TAKEN",
	3: "VALIDATION_ERROR",
}
var Result_SignUpResult_SignUpResultStatus_value = map[string]int32{
	"SIGNED_UP":         1,
	"USERNAME_IS_TAKEN": 2,
	"VALIDATION_ERROR":  3,
}

func (x Result_SignUpResult_SignUpResultStatus) Enum() *Result_SignUpResult_SignUpResultStatus {
	p := new(Result_SignUpResult_SignUpResultStatus)
	*p = x
	return p
}
func (x Result_SignUpResult_SignUpResultStatus) String() string {
	return proto.EnumName(Result_SignUpResult_SignUpResultStatus_name, int32(x))
}
func (x *Result_SignUpResult_SignUpResultStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Result_SignUpResult_SignUpResultStatus_value, data, "Result_SignUpResult_SignUpResultStatus")
	if err != nil {
		return err
	}
	*x = Result_SignUpResult_SignUpResultStatus(value)
	return nil
}
func (Result_SignUpResult_SignUpResultStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 0, 0}
}

type Result_SignInResult_SignInResultStatus int32

const (
	Result_SignInResult_SIGNED_IN      Result_SignInResult_SignInResultStatus = 1
	Result_SignInResult_USER_NOT_FOUND Result_SignInResult_SignInResultStatus = 2
)

var Result_SignInResult_SignInResultStatus_name = map[int32]string{
	1: "SIGNED_IN",
	2: "USER_NOT_FOUND",
}
var Result_SignInResult_SignInResultStatus_value = map[string]int32{
	"SIGNED_IN":      1,
	"USER_NOT_FOUND": 2,
}

func (x Result_SignInResult_SignInResultStatus) Enum() *Result_SignInResult_SignInResultStatus {
	p := new(Result_SignInResult_SignInResultStatus)
	*p = x
	return p
}
func (x Result_SignInResult_SignInResultStatus) String() string {
	return proto.EnumName(Result_SignInResult_SignInResultStatus_name, int32(x))
}
func (x *Result_SignInResult_SignInResultStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Result_SignInResult_SignInResultStatus_value, data, "Result_SignInResult_SignInResultStatus")
	if err != nil {
		return err
	}
	*x = Result_SignInResult_SignInResultStatus(value)
	return nil
}
func (Result_SignInResult_SignInResultStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 1, 0}
}

type Result_SendMessageToUserResult_SendMessageToUserResultStatus int32

const (
	Result_SendMessageToUserResult_SENT           Result_SendMessageToUserResult_SendMessageToUserResultStatus = 1
	Result_SendMessageToUserResult_USER_NOT_FOUND Result_SendMessageToUserResult_SendMessageToUserResultStatus = 2
	Result_SendMessageToUserResult_EMPTY_MESSAGE  Result_SendMessageToUserResult_SendMessageToUserResultStatus = 3
)

var Result_SendMessageToUserResult_SendMessageToUserResultStatus_name = map[int32]string{
	1: "SENT",
	2: "USER_NOT_FOUND",
	3: "EMPTY_MESSAGE",
}
var Result_SendMessageToUserResult_SendMessageToUserResultStatus_value = map[string]int32{
	"SENT":           1,
	"USER_NOT_FOUND": 2,
	"EMPTY_MESSAGE":  3,
}

func (x Result_SendMessageToUserResult_SendMessageToUserResultStatus) Enum() *Result_SendMessageToUserResult_SendMessageToUserResultStatus {
	p := new(Result_SendMessageToUserResult_SendMessageToUserResultStatus)
	*p = x
	return p
}
func (x Result_SendMessageToUserResult_SendMessageToUserResultStatus) String() string {
	return proto.EnumName(Result_SendMessageToUserResult_SendMessageToUserResultStatus_name, int32(x))
}
func (x *Result_SendMessageToUserResult_SendMessageToUserResultStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Result_SendMessageToUserResult_SendMessageToUserResultStatus_value, data, "Result_SendMessageToUserResult_SendMessageToUserResultStatus")
	if err != nil {
		return err
	}
	*x = Result_SendMessageToUserResult_SendMessageToUserResultStatus(value)
	return nil
}
func (Result_SendMessageToUserResult_SendMessageToUserResultStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 4, 0}
}

type Message struct {
	Author           *string `protobuf:"bytes,1,req,name=author" json:"author,omitempty"`
	Text             *string `protobuf:"bytes,2,req,name=text" json:"text,omitempty"`
	Date             *int64  `protobuf:"varint,3,req,name=date" json:"date,omitempty"`
	Receiver         *string `protobuf:"bytes,4,req,name=receiver" json:"receiver,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetAuthor() string {
	if m != nil && m.Author != nil {
		return *m.Author
	}
	return ""
}

func (m *Message) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *Message) GetDate() int64 {
	if m != nil && m.Date != nil {
		return *m.Date
	}
	return 0
}

func (m *Message) GetReceiver() string {
	if m != nil && m.Receiver != nil {
		return *m.Receiver
	}
	return ""
}

type User struct {
	Username         *string `protobuf:"bytes,1,req,name=username" json:"username,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *User) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

type Request struct {
	Id *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	// Types that are valid to be assigned to Action:
	//	*Request_SignUp_
	//	*Request_SignIn_
	//	*Request_GetUsers_
	//	*Request_GetMessagesWithUser_
	//	*Request_SendMessageToUser_
	Action           isRequest_Action `protobuf_oneof:"action"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isRequest_Action interface {
	isRequest_Action()
}

type Request_SignUp_ struct {
	SignUp *Request_SignUp `protobuf:"bytes,2,opt,name=sign_up,oneof"`
}
type Request_SignIn_ struct {
	SignIn *Request_SignIn `protobuf:"bytes,3,opt,name=sign_in,oneof"`
}
type Request_GetUsers_ struct {
	GetUsers *Request_GetUsers `protobuf:"bytes,4,opt,name=get_users,oneof"`
}
type Request_GetMessagesWithUser_ struct {
	GetMessagesWithUser *Request_GetMessagesWithUser `protobuf:"bytes,5,opt,name=get_messages_with_user,oneof"`
}
type Request_SendMessageToUser_ struct {
	SendMessageToUser *Request_SendMessageToUser `protobuf:"bytes,6,opt,name=send_message_to_user,oneof"`
}

func (*Request_SignUp_) isRequest_Action()              {}
func (*Request_SignIn_) isRequest_Action()              {}
func (*Request_GetUsers_) isRequest_Action()            {}
func (*Request_GetMessagesWithUser_) isRequest_Action() {}
func (*Request_SendMessageToUser_) isRequest_Action()   {}

func (m *Request) GetAction() isRequest_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *Request) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Request) GetSignUp() *Request_SignUp {
	if x, ok := m.GetAction().(*Request_SignUp_); ok {
		return x.SignUp
	}
	return nil
}

func (m *Request) GetSignIn() *Request_SignIn {
	if x, ok := m.GetAction().(*Request_SignIn_); ok {
		return x.SignIn
	}
	return nil
}

func (m *Request) GetGetUsers() *Request_GetUsers {
	if x, ok := m.GetAction().(*Request_GetUsers_); ok {
		return x.GetUsers
	}
	return nil
}

func (m *Request) GetGetMessagesWithUser() *Request_GetMessagesWithUser {
	if x, ok := m.GetAction().(*Request_GetMessagesWithUser_); ok {
		return x.GetMessagesWithUser
	}
	return nil
}

func (m *Request) GetSendMessageToUser() *Request_SendMessageToUser {
	if x, ok := m.GetAction().(*Request_SendMessageToUser_); ok {
		return x.SendMessageToUser
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Request) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Request_OneofMarshaler, _Request_OneofUnmarshaler, _Request_OneofSizer, []interface{}{
		(*Request_SignUp_)(nil),
		(*Request_SignIn_)(nil),
		(*Request_GetUsers_)(nil),
		(*Request_GetMessagesWithUser_)(nil),
		(*Request_SendMessageToUser_)(nil),
	}
}

func _Request_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Request)
	// action
	switch x := m.Action.(type) {
	case *Request_SignUp_:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SignUp); err != nil {
			return err
		}
	case *Request_SignIn_:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SignIn); err != nil {
			return err
		}
	case *Request_GetUsers_:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetUsers); err != nil {
			return err
		}
	case *Request_GetMessagesWithUser_:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetMessagesWithUser); err != nil {
			return err
		}
	case *Request_SendMessageToUser_:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SendMessageToUser); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Request.Action has unexpected type %T", x)
	}
	return nil
}

func _Request_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Request)
	switch tag {
	case 2: // action.sign_up
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Request_SignUp)
		err := b.DecodeMessage(msg)
		m.Action = &Request_SignUp_{msg}
		return true, err
	case 3: // action.sign_in
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Request_SignIn)
		err := b.DecodeMessage(msg)
		m.Action = &Request_SignIn_{msg}
		return true, err
	case 4: // action.get_users
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Request_GetUsers)
		err := b.DecodeMessage(msg)
		m.Action = &Request_GetUsers_{msg}
		return true, err
	case 5: // action.get_messages_with_user
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Request_GetMessagesWithUser)
		err := b.DecodeMessage(msg)
		m.Action = &Request_GetMessagesWithUser_{msg}
		return true, err
	case 6: // action.send_message_to_user
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Request_SendMessageToUser)
		err := b.DecodeMessage(msg)
		m.Action = &Request_SendMessageToUser_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Request_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Request)
	// action
	switch x := m.Action.(type) {
	case *Request_SignUp_:
		s := proto.Size(x.SignUp)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_SignIn_:
		s := proto.Size(x.SignIn)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_GetUsers_:
		s := proto.Size(x.GetUsers)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_GetMessagesWithUser_:
		s := proto.Size(x.GetMessagesWithUser)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_SendMessageToUser_:
		s := proto.Size(x.SendMessageToUser)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Request_SignUp struct {
	Username         *string `protobuf:"bytes,1,req,name=username" json:"username,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request_SignUp) Reset()                    { *m = Request_SignUp{} }
func (m *Request_SignUp) String() string            { return proto.CompactTextString(m) }
func (*Request_SignUp) ProtoMessage()               {}
func (*Request_SignUp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *Request_SignUp) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *Request_SignUp) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type Request_SignIn struct {
	Username         *string `protobuf:"bytes,1,req,name=username" json:"username,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request_SignIn) Reset()                    { *m = Request_SignIn{} }
func (m *Request_SignIn) String() string            { return proto.CompactTextString(m) }
func (*Request_SignIn) ProtoMessage()               {}
func (*Request_SignIn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1} }

func (m *Request_SignIn) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *Request_SignIn) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type Request_GetUsers struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Request_GetUsers) Reset()                    { *m = Request_GetUsers{} }
func (m *Request_GetUsers) String() string            { return proto.CompactTextString(m) }
func (*Request_GetUsers) ProtoMessage()               {}
func (*Request_GetUsers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 2} }

type Request_GetMessagesWithUser struct {
	With             *string `protobuf:"bytes,1,req,name=with" json:"with,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request_GetMessagesWithUser) Reset()                    { *m = Request_GetMessagesWithUser{} }
func (m *Request_GetMessagesWithUser) String() string            { return proto.CompactTextString(m) }
func (*Request_GetMessagesWithUser) ProtoMessage()               {}
func (*Request_GetMessagesWithUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 3} }

func (m *Request_GetMessagesWithUser) GetWith() string {
	if m != nil && m.With != nil {
		return *m.With
	}
	return ""
}

type Request_SendMessageToUser struct {
	Receiver         *string `protobuf:"bytes,1,req,name=receiver" json:"receiver,omitempty"`
	Text             *string `protobuf:"bytes,2,req,name=text" json:"text,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request_SendMessageToUser) Reset()                    { *m = Request_SendMessageToUser{} }
func (m *Request_SendMessageToUser) String() string            { return proto.CompactTextString(m) }
func (*Request_SendMessageToUser) ProtoMessage()               {}
func (*Request_SendMessageToUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 4} }

func (m *Request_SendMessageToUser) GetReceiver() string {
	if m != nil && m.Receiver != nil {
		return *m.Receiver
	}
	return ""
}

func (m *Request_SendMessageToUser) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

type Result struct {
	Id *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Result_SignUp
	//	*Result_SignIn
	//	*Result_GetUsers
	//	*Result_GetMessagesWithUser
	//	*Result_SendMessageToUser
	Value            isResult_Value `protobuf_oneof:"value"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isResult_Value interface {
	isResult_Value()
}

type Result_SignUp struct {
	SignUp *Result_SignUpResult `protobuf:"bytes,2,opt,name=sign_up,oneof"`
}
type Result_SignIn struct {
	SignIn *Result_SignInResult `protobuf:"bytes,3,opt,name=sign_in,oneof"`
}
type Result_GetUsers struct {
	GetUsers *Result_GetUsersResult `protobuf:"bytes,4,opt,name=get_users,oneof"`
}
type Result_GetMessagesWithUser struct {
	GetMessagesWithUser *Result_GetMessagesWithUserResult `protobuf:"bytes,5,opt,name=get_messages_with_user,oneof"`
}
type Result_SendMessageToUser struct {
	SendMessageToUser *Result_SendMessageToUserResult `protobuf:"bytes,6,opt,name=send_message_to_user,oneof"`
}

func (*Result_SignUp) isResult_Value()              {}
func (*Result_SignIn) isResult_Value()              {}
func (*Result_GetUsers) isResult_Value()            {}
func (*Result_GetMessagesWithUser) isResult_Value() {}
func (*Result_SendMessageToUser) isResult_Value()   {}

func (m *Result) GetValue() isResult_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Result) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Result) GetSignUp() *Result_SignUpResult {
	if x, ok := m.GetValue().(*Result_SignUp); ok {
		return x.SignUp
	}
	return nil
}

func (m *Result) GetSignIn() *Result_SignInResult {
	if x, ok := m.GetValue().(*Result_SignIn); ok {
		return x.SignIn
	}
	return nil
}

func (m *Result) GetGetUsers() *Result_GetUsersResult {
	if x, ok := m.GetValue().(*Result_GetUsers); ok {
		return x.GetUsers
	}
	return nil
}

func (m *Result) GetGetMessagesWithUser() *Result_GetMessagesWithUserResult {
	if x, ok := m.GetValue().(*Result_GetMessagesWithUser); ok {
		return x.GetMessagesWithUser
	}
	return nil
}

func (m *Result) GetSendMessageToUser() *Result_SendMessageToUserResult {
	if x, ok := m.GetValue().(*Result_SendMessageToUser); ok {
		return x.SendMessageToUser
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Result) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Result_OneofMarshaler, _Result_OneofUnmarshaler, _Result_OneofSizer, []interface{}{
		(*Result_SignUp)(nil),
		(*Result_SignIn)(nil),
		(*Result_GetUsers)(nil),
		(*Result_GetMessagesWithUser)(nil),
		(*Result_SendMessageToUser)(nil),
	}
}

func _Result_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Result)
	// value
	switch x := m.Value.(type) {
	case *Result_SignUp:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SignUp); err != nil {
			return err
		}
	case *Result_SignIn:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SignIn); err != nil {
			return err
		}
	case *Result_GetUsers:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetUsers); err != nil {
			return err
		}
	case *Result_GetMessagesWithUser:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetMessagesWithUser); err != nil {
			return err
		}
	case *Result_SendMessageToUser:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SendMessageToUser); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Result.Value has unexpected type %T", x)
	}
	return nil
}

func _Result_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Result)
	switch tag {
	case 2: // value.sign_up
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Result_SignUpResult)
		err := b.DecodeMessage(msg)
		m.Value = &Result_SignUp{msg}
		return true, err
	case 3: // value.sign_in
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Result_SignInResult)
		err := b.DecodeMessage(msg)
		m.Value = &Result_SignIn{msg}
		return true, err
	case 4: // value.get_users
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Result_GetUsersResult)
		err := b.DecodeMessage(msg)
		m.Value = &Result_GetUsers{msg}
		return true, err
	case 5: // value.get_messages_with_user
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Result_GetMessagesWithUserResult)
		err := b.DecodeMessage(msg)
		m.Value = &Result_GetMessagesWithUser{msg}
		return true, err
	case 6: // value.send_message_to_user
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Result_SendMessageToUserResult)
		err := b.DecodeMessage(msg)
		m.Value = &Result_SendMessageToUser{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Result_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Result)
	// value
	switch x := m.Value.(type) {
	case *Result_SignUp:
		s := proto.Size(x.SignUp)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Result_SignIn:
		s := proto.Size(x.SignIn)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Result_GetUsers:
		s := proto.Size(x.GetUsers)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Result_GetMessagesWithUser:
		s := proto.Size(x.GetMessagesWithUser)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Result_SendMessageToUser:
		s := proto.Size(x.SendMessageToUser)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Result_SignUpResult struct {
	Status           *Result_SignUpResult_SignUpResultStatus `protobuf:"varint,1,req,name=status,enum=HseMsg.Result_SignUpResult_SignUpResultStatus" json:"status,omitempty"`
	XXX_unrecognized []byte                                  `json:"-"`
}

func (m *Result_SignUpResult) Reset()                    { *m = Result_SignUpResult{} }
func (m *Result_SignUpResult) String() string            { return proto.CompactTextString(m) }
func (*Result_SignUpResult) ProtoMessage()               {}
func (*Result_SignUpResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func (m *Result_SignUpResult) GetStatus() Result_SignUpResult_SignUpResultStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Result_SignUpResult_SIGNED_UP
}

type Result_SignInResult struct {
	Status           *Result_SignInResult_SignInResultStatus `protobuf:"varint,1,req,name=status,enum=HseMsg.Result_SignInResult_SignInResultStatus" json:"status,omitempty"`
	XXX_unrecognized []byte                                  `json:"-"`
}

func (m *Result_SignInResult) Reset()                    { *m = Result_SignInResult{} }
func (m *Result_SignInResult) String() string            { return proto.CompactTextString(m) }
func (*Result_SignInResult) ProtoMessage()               {}
func (*Result_SignInResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 1} }

func (m *Result_SignInResult) GetStatus() Result_SignInResult_SignInResultStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Result_SignInResult_SIGNED_IN
}

type Result_GetUsersResult struct {
	Users            []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Result_GetUsersResult) Reset()                    { *m = Result_GetUsersResult{} }
func (m *Result_GetUsersResult) String() string            { return proto.CompactTextString(m) }
func (*Result_GetUsersResult) ProtoMessage()               {}
func (*Result_GetUsersResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 2} }

func (m *Result_GetUsersResult) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type Result_GetMessagesWithUserResult struct {
	Messages         []*Message `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Result_GetMessagesWithUserResult) Reset()         { *m = Result_GetMessagesWithUserResult{} }
func (m *Result_GetMessagesWithUserResult) String() string { return proto.CompactTextString(m) }
func (*Result_GetMessagesWithUserResult) ProtoMessage()    {}
func (*Result_GetMessagesWithUserResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 3}
}

func (m *Result_GetMessagesWithUserResult) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Result_SendMessageToUserResult struct {
	Status           *Result_SendMessageToUserResult_SendMessageToUserResultStatus `protobuf:"varint,1,req,name=status,enum=HseMsg.Result_SendMessageToUserResult_SendMessageToUserResultStatus" json:"status,omitempty"`
	XXX_unrecognized []byte                                                        `json:"-"`
}

func (m *Result_SendMessageToUserResult) Reset()         { *m = Result_SendMessageToUserResult{} }
func (m *Result_SendMessageToUserResult) String() string { return proto.CompactTextString(m) }
func (*Result_SendMessageToUserResult) ProtoMessage()    {}
func (*Result_SendMessageToUserResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 4}
}

func (m *Result_SendMessageToUserResult) GetStatus() Result_SendMessageToUserResult_SendMessageToUserResultStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Result_SendMessageToUserResult_SENT
}

type Event struct {
	// Types that are valid to be assigned to Event:
	//	*Event_NewMessage_
	//	*Event_NewUser_
	Event            isEvent_Event `protobuf_oneof:"event"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type isEvent_Event interface {
	isEvent_Event()
}

type Event_NewMessage_ struct {
	NewMessage *Event_NewMessage `protobuf:"bytes,1,opt,name=new_message,oneof"`
}
type Event_NewUser_ struct {
	NewUser *Event_NewUser `protobuf:"bytes,2,opt,name=new_user,oneof"`
}

func (*Event_NewMessage_) isEvent_Event() {}
func (*Event_NewUser_) isEvent_Event()    {}

func (m *Event) GetEvent() isEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Event) GetNewMessage() *Event_NewMessage {
	if x, ok := m.GetEvent().(*Event_NewMessage_); ok {
		return x.NewMessage
	}
	return nil
}

func (m *Event) GetNewUser() *Event_NewUser {
	if x, ok := m.GetEvent().(*Event_NewUser_); ok {
		return x.NewUser
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Event) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Event_OneofMarshaler, _Event_OneofUnmarshaler, _Event_OneofSizer, []interface{}{
		(*Event_NewMessage_)(nil),
		(*Event_NewUser_)(nil),
	}
}

func _Event_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Event)
	// event
	switch x := m.Event.(type) {
	case *Event_NewMessage_:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NewMessage); err != nil {
			return err
		}
	case *Event_NewUser_:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NewUser); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Event.Event has unexpected type %T", x)
	}
	return nil
}

func _Event_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Event)
	switch tag {
	case 1: // event.new_message
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Event_NewMessage)
		err := b.DecodeMessage(msg)
		m.Event = &Event_NewMessage_{msg}
		return true, err
	case 2: // event.new_user
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Event_NewUser)
		err := b.DecodeMessage(msg)
		m.Event = &Event_NewUser_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Event_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Event)
	// event
	switch x := m.Event.(type) {
	case *Event_NewMessage_:
		s := proto.Size(x.NewMessage)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Event_NewUser_:
		s := proto.Size(x.NewUser)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Event_NewMessage struct {
	Message          *Message `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Event_NewMessage) Reset()                    { *m = Event_NewMessage{} }
func (m *Event_NewMessage) String() string            { return proto.CompactTextString(m) }
func (*Event_NewMessage) ProtoMessage()               {}
func (*Event_NewMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

func (m *Event_NewMessage) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type Event_NewUser struct {
	User             *User  `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Event_NewUser) Reset()                    { *m = Event_NewUser{} }
func (m *Event_NewUser) String() string            { return proto.CompactTextString(m) }
func (*Event_NewUser) ProtoMessage()               {}
func (*Event_NewUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 1} }

func (m *Event_NewUser) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type ServerMessage struct {
	// Types that are valid to be assigned to Message:
	//	*ServerMessage_Event
	//	*ServerMessage_Result
	Message          isServerMessage_Message `protobuf_oneof:"message"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *ServerMessage) Reset()                    { *m = ServerMessage{} }
func (m *ServerMessage) String() string            { return proto.CompactTextString(m) }
func (*ServerMessage) ProtoMessage()               {}
func (*ServerMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_Event struct {
	Event *Event `protobuf:"bytes,1,opt,name=event,oneof"`
}
type ServerMessage_Result struct {
	Result *Result `protobuf:"bytes,2,opt,name=result,oneof"`
}

func (*ServerMessage_Event) isServerMessage_Message()  {}
func (*ServerMessage_Result) isServerMessage_Message() {}

func (m *ServerMessage) GetMessage() isServerMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ServerMessage) GetEvent() *Event {
	if x, ok := m.GetMessage().(*ServerMessage_Event); ok {
		return x.Event
	}
	return nil
}

func (m *ServerMessage) GetResult() *Result {
	if x, ok := m.GetMessage().(*ServerMessage_Result); ok {
		return x.Result
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ServerMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ServerMessage_OneofMarshaler, _ServerMessage_OneofUnmarshaler, _ServerMessage_OneofSizer, []interface{}{
		(*ServerMessage_Event)(nil),
		(*ServerMessage_Result)(nil),
	}
}

func _ServerMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ServerMessage)
	// message
	switch x := m.Message.(type) {
	case *ServerMessage_Event:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Event); err != nil {
			return err
		}
	case *ServerMessage_Result:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Result); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ServerMessage.Message has unexpected type %T", x)
	}
	return nil
}

func _ServerMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ServerMessage)
	switch tag {
	case 1: // message.event
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Event)
		err := b.DecodeMessage(msg)
		m.Message = &ServerMessage_Event{msg}
		return true, err
	case 2: // message.result
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Result)
		err := b.DecodeMessage(msg)
		m.Message = &ServerMessage_Result{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ServerMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ServerMessage)
	// message
	switch x := m.Message.(type) {
	case *ServerMessage_Event:
		s := proto.Size(x.Event)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServerMessage_Result:
		s := proto.Size(x.Result)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Message)(nil), "HseMsg.Message")
	proto.RegisterType((*User)(nil), "HseMsg.User")
	proto.RegisterType((*Request)(nil), "HseMsg.Request")
	proto.RegisterType((*Request_SignUp)(nil), "HseMsg.Request.SignUp")
	proto.RegisterType((*Request_SignIn)(nil), "HseMsg.Request.SignIn")
	proto.RegisterType((*Request_GetUsers)(nil), "HseMsg.Request.GetUsers")
	proto.RegisterType((*Request_GetMessagesWithUser)(nil), "HseMsg.Request.GetMessagesWithUser")
	proto.RegisterType((*Request_SendMessageToUser)(nil), "HseMsg.Request.SendMessageToUser")
	proto.RegisterType((*Result)(nil), "HseMsg.Result")
	proto.RegisterType((*Result_SignUpResult)(nil), "HseMsg.Result.SignUpResult")
	proto.RegisterType((*Result_SignInResult)(nil), "HseMsg.Result.SignInResult")
	proto.RegisterType((*Result_GetUsersResult)(nil), "HseMsg.Result.GetUsersResult")
	proto.RegisterType((*Result_GetMessagesWithUserResult)(nil), "HseMsg.Result.GetMessagesWithUserResult")
	proto.RegisterType((*Result_SendMessageToUserResult)(nil), "HseMsg.Result.SendMessageToUserResult")
	proto.RegisterType((*Event)(nil), "HseMsg.Event")
	proto.RegisterType((*Event_NewMessage)(nil), "HseMsg.Event.NewMessage")
	proto.RegisterType((*Event_NewUser)(nil), "HseMsg.Event.NewUser")
	proto.RegisterType((*ServerMessage)(nil), "HseMsg.ServerMessage")
	proto.RegisterEnum("HseMsg.Result_SignUpResult_SignUpResultStatus", Result_SignUpResult_SignUpResultStatus_name, Result_SignUpResult_SignUpResultStatus_value)
	proto.RegisterEnum("HseMsg.Result_SignInResult_SignInResultStatus", Result_SignInResult_SignInResultStatus_name, Result_SignInResult_SignInResultStatus_value)
	proto.RegisterEnum("HseMsg.Result_SendMessageToUserResult_SendMessageToUserResultStatus", Result_SendMessageToUserResult_SendMessageToUserResultStatus_name, Result_SendMessageToUserResult_SendMessageToUserResultStatus_value)
}

func init() { proto.RegisterFile("HseMsg/HseMsg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 732 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x4e, 0xdb, 0x48,
	0x18, 0x25, 0xff, 0xc9, 0x07, 0xc9, 0x86, 0xe1, 0x67, 0xb3, 0x46, 0xac, 0x82, 0xd1, 0xae, 0xa8,
	0x54, 0x8c, 0x44, 0x2f, 0x7a, 0x87, 0x14, 0x14, 0x13, 0xdc, 0x36, 0x0e, 0x8a, 0x9d, 0x56, 0x95,
	0x2a, 0x59, 0x16, 0x19, 0x85, 0x48, 0x60, 0xa7, 0x9e, 0x31, 0xe9, 0x1b, 0xf4, 0x35, 0x7a, 0xd3,
	0x07, 0xa9, 0xfa, 0x42, 0x7d, 0x84, 0xce, 0x78, 0xc6, 0x01, 0xdb, 0x09, 0xe5, 0xca, 0x9a, 0x99,
	0xf3, 0x9d, 0x39, 0xdf, 0x39, 0x9f, 0x07, 0xb6, 0x2e, 0x09, 0xee, 0x93, 0xc9, 0x89, 0xf8, 0x68,
	0xb3, 0xc0, 0xa7, 0x3e, 0x2a, 0x8b, 0x95, 0xda, 0x83, 0x4a, 0x1f, 0x13, 0xe2, 0x4e, 0x30, 0x6a,
	0x40, 0xd9, 0x0d, 0xe9, 0x8d, 0x1f, 0xb4, 0x72, 0xed, 0xfc, 0x51, 0x0d, 0x6d, 0x40, 0x91, 0xe2,
	0x2f, 0xb4, 0x95, 0x8f, 0x57, 0x63, 0x97, 0xe2, 0x56, 0x81, 0xad, 0x0a, 0xa8, 0x09, 0xd5, 0x00,
	0x5f, 0xe3, 0xe9, 0x3d, 0x0e, 0x5a, 0x45, 0x7e, 0xae, 0xb6, 0xa0, 0x38, 0x22, 0x38, 0xe0, 0x27,
	0x21, 0xfb, 0x7a, 0xee, 0x1d, 0x16, 0x3c, 0xea, 0xaf, 0x02, 0x54, 0x86, 0xf8, 0x73, 0x88, 0x09,
	0x45, 0x00, 0xf9, 0xe9, 0x38, 0xda, 0xaf, 0xa3, 0x17, 0x50, 0x21, 0xd3, 0x89, 0xe7, 0x84, 0x33,
	0x76, 0x45, 0xee, 0x68, 0xfd, 0x74, 0x57, 0x93, 0x12, 0x25, 0x5a, 0xb3, 0xd8, 0xf1, 0x68, 0x76,
	0xb9, 0xb6, 0x80, 0x4e, 0x3d, 0x76, 0xff, 0x4a, 0xa8, 0xe1, 0x31, 0xe8, 0x31, 0xd4, 0x26, 0x98,
	0x3a, 0x5c, 0x03, 0x61, 0xd2, 0x38, 0xb8, 0x95, 0x06, 0xf7, 0x30, 0xe5, 0x5a, 0x09, 0x83, 0xeb,
	0xb0, 0xcb, 0xe1, 0x77, 0xc2, 0x03, 0xe2, 0xcc, 0xa7, 0xf4, 0x26, 0x2a, 0x6e, 0x95, 0xa2, 0xda,
	0xc3, 0x25, 0xb5, 0xd2, 0x30, 0xf2, 0x81, 0x61, 0x39, 0x0f, 0xa3, 0xe9, 0xc0, 0x36, 0xc1, 0xde,
	0x38, 0xe6, 0x71, 0xa8, 0x2f, 0x48, 0xca, 0x11, 0xc9, 0x41, 0x46, 0x2d, 0xc3, 0x4a, 0x16, 0xdb,
	0x17, 0x14, 0xca, 0x4b, 0x28, 0x8b, 0x7e, 0xb3, 0x16, 0xf2, 0x9d, 0x99, 0x4b, 0xc8, 0xdc, 0x0f,
	0xc6, 0x22, 0x8e, 0x18, 0x6d, 0x78, 0xcf, 0x42, 0x03, 0x54, 0xe3, 0x9e, 0x95, 0x43, 0xd8, 0x5a,
	0xd2, 0x03, 0xcf, 0x97, 0xf7, 0x2e, 0x28, 0x94, 0x57, 0xb0, 0x99, 0xd1, 0x98, 0x08, 0x7d, 0xc9,
	0x88, 0x9c, 0x57, 0xd9, 0x00, 0x5d, 0xd3, 0xa9, 0xef, 0xa9, 0xdf, 0x2b, 0x50, 0x1e, 0x62, 0x12,
	0xde, 0x26, 0x13, 0xd7, 0xd2, 0x89, 0xef, 0x3d, 0x18, 0xc3, 0xc1, 0x32, 0x70, 0xb1, 0x60, 0xae,
	0x6a, 0xe9, 0xd8, 0x97, 0xe1, 0x0d, 0x6f, 0x81, 0x3f, 0xcd, 0x66, 0xbf, 0x9f, 0xaa, 0x88, 0x6d,
	0x58, 0xd4, 0xbc, 0xf9, 0xc3, 0x00, 0x1c, 0x65, 0x09, 0xd2, 0xde, 0x2d, 0xb8, 0x2e, 0x9e, 0x9c,
	0x82, 0xff, 0xd3, 0xe2, 0xd3, 0x06, 0xc7, 0x3c, 0xca, 0xb7, 0x1c, 0x6c, 0x3c, 0xb6, 0x02, 0x9d,
	0x41, 0x99, 0x50, 0x97, 0x86, 0x24, 0x32, 0xb2, 0x71, 0xaa, 0x3d, 0xe1, 0x5b, 0x62, 0x61, 0x45,
	0x55, 0xea, 0x15, 0xa0, 0xec, 0x2e, 0xaa, 0x43, 0xcd, 0x32, 0x7a, 0xa6, 0xde, 0x75, 0x46, 0x57,
	0xcd, 0x1c, 0xda, 0x81, 0xcd, 0x91, 0xa5, 0x0f, 0xcd, 0x4e, 0x5f, 0x77, 0x0c, 0xcb, 0xb1, 0x3b,
	0x6f, 0x75, 0xb3, 0x99, 0x47, 0xdb, 0xd0, 0x7c, 0xdf, 0x79, 0x67, 0x74, 0x3b, 0xb6, 0x31, 0x30,
	0x1d, 0x7d, 0x38, 0x1c, 0x0c, 0x9b, 0x05, 0xe5, 0xab, 0x94, 0x18, 0xbb, 0xff, 0x2c, 0x89, 0x31,
	0x38, 0xb1, 0x90, 0x12, 0x5f, 0x0b, 0x89, 0xc9, 0xdd, 0x47, 0x12, 0x0d, 0x93, 0x49, 0x44, 0xd0,
	0xe0, 0x12, 0x1d, 0x73, 0x60, 0x3b, 0x17, 0x83, 0x91, 0xd9, 0x6d, 0xe6, 0x95, 0x63, 0x68, 0x24,
	0x43, 0x45, 0x7b, 0x50, 0x12, 0x23, 0x90, 0x6b, 0x17, 0x98, 0xef, 0x1b, 0xb1, 0x12, 0x8e, 0x51,
	0xce, 0xe0, 0x9f, 0x95, 0x11, 0xa2, 0x03, 0xa8, 0xc6, 0x83, 0x20, 0x8b, 0xff, 0x8a, 0x8b, 0x65,
	0x85, 0xf2, 0x23, 0x07, 0x7f, 0xaf, 0x48, 0x0e, 0xd9, 0x29, 0x0f, 0xba, 0xcf, 0x4b, 0x7c, 0xd5,
	0xfe, 0x22, 0xbc, 0xfd, 0x27, 0x01, 0xa8, 0x0a, 0x45, 0x4b, 0x37, 0xed, 0xe5, 0xfe, 0xa0, 0x4d,
	0xa8, 0xeb, 0xfd, 0x2b, 0xfb, 0xa3, 0xd3, 0xd7, 0x2d, 0xab, 0xd3, 0xd3, 0x9b, 0x85, 0xf3, 0x0a,
	0x94, 0xee, 0xdd, 0xdb, 0x10, 0xab, 0x3f, 0x73, 0x50, 0xd2, 0xef, 0xb1, 0x47, 0xd1, 0x09, 0xac,
	0x7b, 0x78, 0x1e, 0x4f, 0x2e, 0xd3, 0x9f, 0x78, 0x38, 0x23, 0x8c, 0x66, 0xe2, 0xb9, 0x14, 0x11,
	0x3d, 0xc9, 0x55, 0x5e, 0x10, 0xcd, 0xb7, 0xf8, 0x99, 0x77, 0x32, 0x68, 0xf9, 0xb2, 0x69, 0x00,
	0x0f, 0xa5, 0xa8, 0x0d, 0x95, 0x87, 0x5b, 0xf2, 0xcb, 0x2c, 0xfe, 0x0f, 0x2a, 0xb2, 0x18, 0x29,
	0x50, 0x8c, 0x6e, 0x10, 0xc8, 0x44, 0x92, 0xbc, 0x0b, 0xcc, 0x6f, 0x52, 0x3f, 0x41, 0xdd, 0xc2,
	0x01, 0x7b, 0x95, 0xe2, 0x2b, 0xfe, 0x95, 0x27, 0xb2, 0x8d, 0x7a, 0x42, 0x18, 0xd3, 0xde, 0x86,
	0x72, 0x10, 0x19, 0x28, 0x95, 0x37, 0x92, 0x39, 0x5d, 0xae, 0x9d, 0xd7, 0x16, 0x22, 0x7f, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x52, 0x45, 0x39, 0x7a, 0x3f, 0x07, 0x00, 0x00,
}
